version: "3.12.1"

services:
  app:
    build:
        context: ./server
    container_name: flask_app
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"   #  prox http
      - "443:443" # prox HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
